sudo: false

language: go

go: 1.4

git:
  submodules: false
  
notifications:
  irc: "chat.freenode.net#seedstack-dev"
  
before_install:
  - git submodule update --init --recursive --remote

install:
  - go get -v github.com/spf13/hugo
  - npm install

script:
  - chmod +x build_diagrams.sh deploy_ghpages.sh
  - ./build_diagrams.sh
  - grunt lunr-index
  - if [ $TRAVIS_BRANCH = master ]; then hugo && echo seedstack.org >| public/CNAME && (curl -o public/distribution.pom.xml https://repo1.maven.org/maven2/org/seedstack/distribution/$SEEDSTACK_STABLE_VERSION/distribution-$SEEDSTACK_STABLE_VERSION.pom || :); fi
  - if [ $TRAVIS_BRANCH = beta ]; then hugo -d beta -b http://beta.seedstack.org/ && echo beta.seedstack.org >| beta/CNAME && (curl -o beta/distribution.pom.xml https://repo1.maven.org/maven2/org/seedstack/distribution/$SEEDSTACK_BETA_VERSION/distribution-$SEEDSTACK_BETA_VERSION.pom || :); fi
  - if [ $TRAVIS_BRANCH = dev ]; then hugo -d dev -b http://dev.seedstack.org/ && echo dev.seedstack.org >| dev/CNAME; fi

after_success:
  - if [ $TRAVIS_PULL_REQUEST = false ] && [ $TRAVIS_BRANCH = master ]; then ./deploy_ghpages.sh && (curl http://www.google.com/webmasters/tools/ping?sitemap=http%3A%2F%2Fseedstack.org%2Fsitemap.xml > /dev/null || :); fi
  - if [ $TRAVIS_PULL_REQUEST = false ] && [ $TRAVIS_BRANCH = beta ]; then ./deploy_ghpages.sh beta; fi
  - if [ $TRAVIS_PULL_REQUEST = false ] && [ $TRAVIS_BRANCH = dev ]; then ./deploy_ghpages.sh dev; fi
